#!/usr/bin/env bash
#
# Test bash-path
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: September 07, 2018
# License: MIT

exit_code=0

banner() {
	echo '#' "$@"
}

equal() {
	local given=$1
	local wanted=$2

	if [[ $wanted != "$given" ]]; then
		cat <<-EOF >&2
		fail: file ${BASH_SOURCE[0]} line ${BASH_LINENO[0]}

		$given != $wanted
		 - given:  '$given'
		 - wanted: '$wanted'

		EOF
		exit_code=1
	fi
}

varEqual() {
	local var=$1
	local wanted=$2
	local given=${!var}

	equal "$given" "$wanted"
}

ensureError() {
	local wanted=$1
	local msg
	local code

	shift

	msg=$("$@" 2>&1)
	code=$?

	equal "$code" 1
	equal "$msg" "$wanted"
}


# we can't continue if we fail to source the library
. path.bash || exit 1

banner 'path_add bad args'
ensureError "path_print_add: invalid argument: ''" path_add
ensureError "path_print_add: invalid argument: '/foo:/bar'" path_add /foo:/bar

banner 'path_remove bad args'
ensureError "path_print_remove: invalid argument: ''" path_remove
ensureError "path_print_remove: invalid argument: '/foo:/bar'" path_remove \
    /foo:/bar

banner 'path_print_add bad args'
ensureError "path_print_add: invalid argument: ''" path_print_add
ensureError "path_print_add: invalid argument: '/foo:/bar'" path_print_add \
    /foo:/bar

banner 'path_print_remove bad args'
ensureError "path_print_remove: invalid argument: ''" path_print_remove
ensureError "path_print_remove: invalid argument: '/foo:/bar'" \
    path_print_remove /foo:/bar

banner 'simple path_add after'
myvar=''
path_add /bin after myvar
varEqual myvar ':/bin'

banner 'simple path_add before'
myvar=''
path_add /bin before myvar
varEqual myvar '/bin:'

banner 'path_add'
myvar='/'
path_add /bin  after  myvar
path_add /sbin after  myvar
path_add /tmp  before myvar
varEqual myvar '/tmp:/:/bin:/sbin'

banner 'path_remove'
path_remove /     myvar
path_remove /foo  myvar
varEqual myvar '/tmp:/bin:/sbin'

banner 'path_add bad directories'
path_add /this-shouldnt-exist after myvar
path_add ./relative-dir       after myvar
varEqual myvar '/tmp:/bin:/sbin:/this-shouldnt-exist:./relative-dir'

banner 'path_clean simple'
path_clean myvar
varEqual myvar '/tmp:/bin:/sbin'

banner 'path_clean complex'
myvar+=':::::.:./:::...:./././::'
path_clean myvar
varEqual myvar '/tmp:/bin:/sbin'

banner 'path_print_remove'
newvar=$(path_print_remove /tmp myvar)
varEqual newvar '/bin:/sbin'
varEqual myvar  '/tmp:/bin:/sbin'

banner 'path_print_add'
newvar=$(path_print_add /tmp after myvar)
varEqual newvar '/tmp:/bin:/sbin:/tmp'
varEqual myvar  '/tmp:/bin:/sbin'

banner 'path_print_clean'
myvar='/bin:/bin/:/bin////:'
clean=$(path_print_clean myvar)
varEqual myvar '/bin:/bin/:/bin////:'
varEqual clean '/bin'

exit "$exit_code"
